### ISSUE TITLE
Folders Missing, Assets, Themes

### ISSUE THREAD

**Issue by cmhulbert** [RohitAwate/Ballad#1]
In order to build, I needed to comment out all lines referring to the Assets directory. For Themes, I was able to just create my own Themes directory, and move the Adreana.css and Oasis.css into the Themes directory.

**Comment by RohitAwate** [comment]
I'm afraid I worked on this project when I didn't have any idea how Git worked. It has been uploaded in a totally wrong fashion. I'll try to upload the project appropriately.

For now, here's a [zip](https://github.com/RohitAwate/Ballad/files/1993947/Ballad.zip) with all the bits and pieces in the right places.

By the way, I'm glad you found interest in Ballad! I've abandoned the project since it was just meant to be a learning effort. However, I'll be glad if you contribute.

**Comment by RohitAwate** [comment]
I've uploaded all the files appropriately so now you can just clone the repository. I've organized them better than the zip I uploaded above. I must warn you though: This was my first ever JavaFX project so the code is quite horrible and a lot of stuff is janky.
Good luck with it! :+1:

**Comment by cmhulbert** [comment]
Thanks for the quick update! I recently started looking into JavaFX, and was looking around for existing projects to get a feel for the framework. I've been interested in my own text editor, so I figured I'd look for existing ones to play around with. Thanks again!

**Comment by RohitAwate** [comment]
That's great! I hope this helps.

Kindly let me know if you can get syntax highlighting to work. All the best! :+1:
